apiVersion: apps/v1
kind: Deployment
metadata:
  name: bananobot-server
  namespace: graham-banano
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bananobot-server
  template:
    metadata:
      labels:
        app: bananobot-server
    spec:
      containers:
      - name: bananobot-server
        image: replaceme
        ports:
        - containerPort: 11337
          name: api
        command: ["/bin/bash", "-c"]
        args: ["cp /config/config.yaml .; python bot.py start_server -p . -s \"rug pull simulator\" -u http://pippin-banano.pippin:11338"]
        env:
          - name: BANANO
            value: "1"
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "8"
          - name: POSTGRES_HOST
            value: pg-bananobot.graham-banano
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bananobot
                key: postgres_password
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bananobot
                key: bot_token
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: bananobot
                key: bpow_key 
          - name: WALLET_ID
            valueFrom:
              secretKeyRef:
                name: bananobot
                key: wallet_id
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: bananobot
                key: api_key
        volumeMounts:
        - name: conf
          mountPath: /config
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: bananobot
          defaultMode: 0755
